server {
    listen 80;
    
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # For React Router to work correctly (SPA)
        try_files $uri $uri/ /index.html;
    }
}
